import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Search, 
  Download, 
  MoreHorizontal, 
  ExternalLink, 
  FileText, 
  Image as ImageIcon,
  Eye,
  Copy,
  Trash2,
  FileCode,
  Check
} from 'lucide-react';
import { ArtifactItem } from '../types';

interface ArtifactsViewProps {
  artifacts: ArtifactItem[];
  onSelectChatReference: (chatRef: string) => void;
  onDownloadFile: (fileName: string) => void;
  onDeleteArtifact?: (id: string) => void;
}

type FilterType = 'All' | 'PDF' | 'Docx' | 'PPT' | 'Code' | '.Md' | 'Txt';

export const ArtifactsView: React.FC<ArtifactsViewProps> = ({
  artifacts,
  onSelectChatReference,
  onDownloadFile,
  onDeleteArtifact,
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedFilter, setSelectedFilter] = useState<FilterType>('All');
  const [activeMenuId, setActiveMenuId] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const filterTabs: FilterType[] = ['All', 'PDF', 'Docx', 'PPT', 'Code', '.Md', 'Txt'];

  const filteredArtifacts = artifacts.filter((art) => {
    const matchesFilter = selectedFilter === 'All' || art.fileType === selectedFilter;
    const matchesSearch =
      art.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      art.chatReference.toLowerCase().includes(searchQuery.toLowerCase()) ||
      art.fileType.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  const handleCopyLink = (id: string, name: string) => {
    navigator.clipboard.writeText(`https://sovara.ai/artifacts/${id}/${encodeURIComponent(name)}`);
    setCopiedId(id);
    setTimeout(() => {
      setCopiedId(null);
      setActiveMenuId(null);
    }, 1500);
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-[#0a0a0d] p-5 md:p-8 lg:p-10 overflow-hidden select-none">
      {/* Header section */}
      <div className="mb-6 space-y-1">
        <h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">
          Artifacts
        </h1>
        <p className="text-xs text-[#71717a]">
          All the files generated by sovara for you
        </p>
      </div>

      {/* Control bar: Search Input & Filter Tabs */}
      <div className="flex flex-col lg:flex-row items-stretch lg:items-center justify-between gap-4 mb-6">
        {/* Search Input Box matching Artifacts.svg */}
        <div className="relative w-full lg:w-80">
          <Search size={15} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#71717a]" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search local files"
            className="w-full bg-[#141419] border border-[#24242f] rounded-xl pl-9 pr-4 py-2 text-xs md:text-sm text-white placeholder-[#686873] focus:outline-none focus:border-[#3a3a48] transition-colors"
          />
        </div>

        {/* Category Filter Pills matching Artifacts.svg */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 lg:pb-0 scrollbar-none">
          {filterTabs.map((tab) => {
            const isSelected = selectedFilter === tab;
            return (
              <button
                key={tab}
                onClick={() => setSelectedFilter(tab)}
                className={`px-3.5 py-1.5 rounded-full text-xs font-medium transition-all shrink-0 ${
                  isSelected
                    ? 'bg-[#1e1e26] text-white border border-[#363644] shadow-sm'
                    : 'text-[#848492] hover:text-white bg-[#121217] hover:bg-[#181820] border border-[#1e1e26]'
                }`}
              >
                {tab}
              </button>
            );
          })}
        </div>
      </div>

      {/* Table Container / Empty View */}
      <div className="flex-1 overflow-y-auto rounded-xl border border-[#1b1b22] bg-[#0c0c0f]">
        {filteredArtifacts.length === 0 ? (
          /* Empty State matching Artifacts_Empty.svg */
          <div className="h-full min-h-[380px] flex flex-col items-center justify-center p-8 text-center">
            <h3 className="text-xl md:text-2xl font-bold text-white/90 max-w-md tracking-tight leading-relaxed">
              All generated artifacts will appear on this screen
            </h3>
            <p className="text-xs text-[#6e6e7a] mt-2 max-w-sm">
              Use Sovara chat to research, generate code, synthesize documents, and export tables.
            </p>
          </div>
        ) : (
          <div className="min-w-[760px]">
            {/* Table Header Row */}
            <div className="grid grid-cols-12 gap-4 px-5 py-3 text-[11px] font-semibold tracking-wider text-[#71717a] border-b border-[#18181f]">
              <div className="col-span-5">File Name</div>
              <div className="col-span-2">File type</div>
              <div className="col-span-2">Generated on</div>
              <div className="col-span-2">Chat reference</div>
              <div className="col-span-1 text-right">Actions</div>
            </div>

            {/* Table Rows */}
            <div className="divide-y divide-[#14141a]">
              {filteredArtifacts.map((art) => (
                <div
                  key={art.id}
                  className="grid grid-cols-12 gap-4 px-5 py-3.5 items-center hover:bg-[#111116] transition-colors group relative"
                >
                  {/* File Name with Document/Image Icon */}
                  <div className="col-span-5 flex items-center gap-3 min-w-0">
                    <div className="p-2 rounded-lg bg-[#15151c] text-[#71717a] group-hover:text-[#7adfd4] border border-[#22222c] transition-colors shrink-0">
                      {art.fileType === 'Code' ? (
                        <FileCode size={16} />
                      ) : (
                        <ImageIcon size={16} />
                      )}
                    </div>
                    <div className="min-w-0">
                      <div className="text-xs md:text-[13px] font-medium text-white/90 truncate">
                        {art.name}
                      </div>
                      <div className="text-[11px] text-[#71717a]">
                        {art.pages} pages • uploaded on {art.uploadedDate}
                      </div>
                    </div>
                  </div>

                  {/* File Type */}
                  <div className="col-span-2 text-xs font-semibold text-white/80">
                    {art.fileType}
                  </div>

                  {/* Generated on */}
                  <div className="col-span-2 text-xs text-[#9a9aa5]">
                    {art.generatedOn}
                  </div>

                  {/* Chat reference */}
                  <div className="col-span-2">
                    <button
                      onClick={() => onSelectChatReference(art.chatReference)}
                      className="flex items-center gap-1.5 text-xs text-[#d4d4dc] hover:text-[#7adfd4] transition-colors group/link truncate text-left"
                    >
                      <span className="truncate">{art.chatReference}</span>
                      <ExternalLink size={12} className="shrink-0 opacity-70 group-hover/link:opacity-100 transition-opacity" />
                    </button>
                  </div>

                  {/* Action Icons: Download & More options */}
                  <div className="col-span-1 flex items-center justify-end gap-1 relative">
                    <button
                      onClick={() => onDownloadFile(`${art.name}.${art.fileType.toLowerCase()}`)}
                      className="p-1.5 rounded-lg text-[#71717a] hover:text-white hover:bg-[#1a1a22] transition-colors"
                      title="Download file"
                      aria-label="Download file"
                    >
                      <Download size={14} />
                    </button>

                    <button
                      onClick={() => setActiveMenuId(activeMenuId === art.id ? null : art.id)}
                      className="p-1.5 rounded-lg text-[#71717a] hover:text-white hover:bg-[#1a1a22] transition-colors"
                      title="More options"
                      aria-label="More options"
                    >
                      <MoreHorizontal size={14} />
                    </button>

                    {/* Options Popover Menu (Artifacts_options.svg) */}
                    <AnimatePresence>
                      {activeMenuId === art.id && (
                        <>
                          <div
                            className="fixed inset-0 z-30"
                            onClick={() => setActiveMenuId(null)}
                          />
                          <motion.div
                            initial={{ opacity: 0, scale: 0.95, y: -4 }}
                            animate={{ opacity: 1, scale: 1, y: 0 }}
                            exit={{ opacity: 0, scale: 0.95, y: -4 }}
                            transition={{ duration: 0.15 }}
                            className="absolute right-0 top-9 z-40 w-44 bg-[#121217] border border-[#262633] rounded-xl shadow-2xl py-1 text-xs select-none"
                          >
                            <button
                              onClick={() => {
                                onDownloadFile(art.name);
                                setActiveMenuId(null);
                              }}
                              className="w-full flex items-center gap-2.5 px-3 py-2 text-[#d4d4dc] hover:text-white hover:bg-[#1a1a24] transition-colors text-left"
                            >
                              <Eye size={13} />
                              <span>Preview</span>
                            </button>

                            <button
                              onClick={() => {
                                onDownloadFile(`${art.name}.${art.fileType.toLowerCase()}`);
                                setActiveMenuId(null);
                              }}
                              className="w-full flex items-center gap-2.5 px-3 py-2 text-[#d4d4dc] hover:text-white hover:bg-[#1a1a24] transition-colors text-left"
                            >
                              <Download size={13} />
                              <span>Download</span>
                            </button>

                            <button
                              onClick={() => handleCopyLink(art.id, art.name)}
                              className="w-full flex items-center gap-2.5 px-3 py-2 text-[#d4d4dc] hover:text-white hover:bg-[#1a1a24] transition-colors text-left"
                            >
                              {copiedId === art.id ? (
                                <Check size={13} className="text-[#34d399]" />
                              ) : (
                                <Copy size={13} />
                              )}
                              <span>{copiedId === art.id ? 'Copied Link' : 'Copy link'}</span>
                            </button>

                            {onDeleteArtifact && (
                              <button
                                onClick={() => {
                                  onDeleteArtifact(art.id);
                                  setActiveMenuId(null);
                                }}
                                className="w-full flex items-center gap-2.5 px-3 py-2 text-[#f87171] hover:text-[#fca5a5] hover:bg-[#250d11] transition-colors text-left border-t border-[#1e1e28] mt-1"
                              >
                                <Trash2 size={13} />
                                <span>Delete artifact</span>
                              </button>
                            )}
                          </motion.div>
                        </>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
